title:             Clean Blog
email:             dstriker@corus360.com
description:       A Blog Theme by Start Bootstrap
author:            David Striker
baseurl:           ""
url:               "https://strikerdd.github.io/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   Strikerdd
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
