title:             IT Collaboration Blog
email:             djstrik888@gmail.com
description:       Knowledge Base for Collaboration and Support Efforts. 
author:            David Striker
baseurl:           ""
url:               "https://strikerdd.github.io/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   Strikerdd
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
